language: node_js
node_js:
    - stable
install:
    - npm install
cache:
    directories:
        - node_modules
before_script:
    - npm install -g gulp-cli
script:
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: '$GITHUB_TOKEN'
    local_dir: build
    keep_history: true
    on:
        branch: master
env:
    global:
        secure: 3AsfT/SS1JJkaVn7taQy/+jvQ4APY2xroB1a+S3t5TEwCgS+T1wRcSktF5z1911qLnJZ6BNr6tud9GEU1pi7rgNvMzpNbhv/oAhPzXFZjzrtXo2u0BWAHQY5jDgQJq9dxjVL10F66P5OH7LOlzagh+YkBrL1z4dLAtG8PXc0M9g21T4Ai/zUkTMtDjJIb56lJ5+3BIgougpaRKSPVO4HDqa2GIZpCeHSMMWwKGHXIPoT1uOyrMPA4nlB6PPdR+oA4Qf5a530D4C6O35VGldvWCO/ngXJIpidQt2QGb7fqZWcdt79pwe7RHKQ0cGJBNivpyxEIXubrn4GX63vMAt09BjAO2HeMh6Y/Nv5O+Mork1U9OLF/RrldBgRfOPeYzw3VLRDcwsub2vuHaehEIQ+JiIW6EPzdJ61LfNU0iAkSLLt31u4O8ABppcgef+Jm7nH31YmsT5qcT2IjOhbLdt0kcISP0e84zBSgmKF2T8ZZIsZY5lMcYaxSxm1BV4caD30JCVZfhKQvXUsRMBqrR9l6/zUZv8RZPC0uZx4aGTSyrMusMNpChL1QeGV+hzfLdZSe51t1LQ08eYXsEFNCyVSb7321emiledtFADO6lSSBCUYhyF/zacW/lTbqN5q7QLRe4i8iukMgGy3OVT1SF2ac25gv4BcAx2hz92vDEFJmFg=
